---
# configure ntp
- name: COMMON Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: COMMON Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp
