---
- name: COMMON Create the repository for EPEL
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: COMMON Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: COMMON Create the repo for local packages
  copy: src=local.repo dest=/etc/yum.repos.d/local.repo

- name: COMMON Install Packages
  yum: name={{ item }} state=present
  with_items:
    - yum-plugin-priorities
    - git
    - ntp
    - ansible
    - python-boto
